<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: ContactRequest.proto
//   Date: 2016-08-04 01:45:57

namespace Ricochet\Channel\ContactRequest\Proto {

  class ContactRequest extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $nickname = null;
    
    /**  @var string */
    public $message_text = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Ricochet.Channel.ContactRequest.ContactRequest');

      // OPTIONAL STRING nickname = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "nickname";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING message_text = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "message_text";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <nickname> has a value
     *
     * @return boolean
     */
    public function hasNickname(){
      return $this->_has(1);
    }
    
    /**
     * Clear <nickname> value
     *
     * @return \Ricochet\Channel\ContactRequest\Proto\ContactRequest
     */
    public function clearNickname(){
      return $this->_clear(1);
    }
    
    /**
     * Get <nickname> value
     *
     * @return string
     */
    public function getNickname(){
      return $this->_get(1);
    }
    
    /**
     * Set <nickname> value
     *
     * @param string $value
     * @return \Ricochet\Channel\ContactRequest\Proto\ContactRequest
     */
    public function setNickname( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <message_text> has a value
     *
     * @return boolean
     */
    public function hasMessageText(){
      return $this->_has(2);
    }
    
    /**
     * Clear <message_text> value
     *
     * @return \Ricochet\Channel\ContactRequest\Proto\ContactRequest
     */
    public function clearMessageText(){
      return $this->_clear(2);
    }
    
    /**
     * Get <message_text> value
     *
     * @return string
     */
    public function getMessageText(){
      return $this->_get(2);
    }
    
    /**
     * Set <message_text> value
     *
     * @param string $value
     * @return \Ricochet\Channel\ContactRequest\Proto\ContactRequest
     */
    public function setMessageText( $value){
      return $this->_set(2, $value);
    }
  }
}

