<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: ContactRequest.proto
//   Date: 2016-08-04 01:45:57

namespace Ricochet\Channel\ContactRequest\Proto {

  class Response extends \DrSlump\Protobuf\Message {

    /**  @var int - \Ricochet\Channel\ContactRequest\Proto\Response\Status */
    public $status = null;
    
    /**  @var string */
    public $error_message = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Ricochet.Channel.ContactRequest.Response');

      // REQUIRED ENUM status = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "status";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $f->reference = '\Ricochet\Channel\ContactRequest\Proto\Response\Status';
      $descriptor->addField($f);

      // OPTIONAL STRING error_message = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "error_message";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <status> has a value
     *
     * @return boolean
     */
    public function hasStatus(){
      return $this->_has(1);
    }
    
    /**
     * Clear <status> value
     *
     * @return \Ricochet\Channel\ContactRequest\Proto\Response
     */
    public function clearStatus(){
      return $this->_clear(1);
    }
    
    /**
     * Get <status> value
     *
     * @return int - \Ricochet\Channel\ContactRequest\Proto\Response\Status
     */
    public function getStatus(){
      return $this->_get(1);
    }
    
    /**
     * Set <status> value
     *
     * @param int - \Ricochet\Channel\ContactRequest\Proto\Response\Status $value
     * @return \Ricochet\Channel\ContactRequest\Proto\Response
     */
    public function setStatus( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <error_message> has a value
     *
     * @return boolean
     */
    public function hasErrorMessage(){
      return $this->_has(2);
    }
    
    /**
     * Clear <error_message> value
     *
     * @return \Ricochet\Channel\ContactRequest\Proto\Response
     */
    public function clearErrorMessage(){
      return $this->_clear(2);
    }
    
    /**
     * Get <error_message> value
     *
     * @return string
     */
    public function getErrorMessage(){
      return $this->_get(2);
    }
    
    /**
     * Set <error_message> value
     *
     * @param string $value
     * @return \Ricochet\Channel\ContactRequest\Proto\Response
     */
    public function setErrorMessage( $value){
      return $this->_set(2, $value);
    }
  }
}

