<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: ContactRequest.proto
//   Date: 2016-08-04 01:45:57

namespace Ricochet\Channel\ContactRequest\Proto\Response {

  class Status extends \DrSlump\Protobuf\Enum {
    const Undefined = 0;
    const Pending = 1;
    const Accepted = 2;
    const Rejected = 3;
    const Error = 4;
  }
}
