<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: Control.proto
//   Date: 2016-08-04 01:45:57

namespace Ricochet\Channel\Control\Proto {

  class ChannelResult extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $channel_identifier = null;
    
    /**  @var boolean */
    public $opened = null;
    
    /**  @var int - \Ricochet\Channel\Control\Proto\ChannelResult\CommonError */
    public $common_error = null;
    
    /**  @var string */
    public $error_message = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Ricochet.Channel.Control.ChannelResult');

      // REQUIRED INT32 channel_identifier = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "channel_identifier";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED BOOL opened = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "opened";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // OPTIONAL ENUM common_error = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "common_error";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\Ricochet\Channel\Control\Proto\ChannelResult\CommonError';
      $descriptor->addField($f);

      // OPTIONAL STRING error_message = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "error_message";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <channel_identifier> has a value
     *
     * @return boolean
     */
    public function hasChannelIdentifier(){
      return $this->_has(1);
    }
    
    /**
     * Clear <channel_identifier> value
     *
     * @return \Ricochet\Channel\Control\Proto\ChannelResult
     */
    public function clearChannelIdentifier(){
      return $this->_clear(1);
    }
    
    /**
     * Get <channel_identifier> value
     *
     * @return int
     */
    public function getChannelIdentifier(){
      return $this->_get(1);
    }
    
    /**
     * Set <channel_identifier> value
     *
     * @param int $value
     * @return \Ricochet\Channel\Control\Proto\ChannelResult
     */
    public function setChannelIdentifier( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <opened> has a value
     *
     * @return boolean
     */
    public function hasOpened(){
      return $this->_has(2);
    }
    
    /**
     * Clear <opened> value
     *
     * @return \Ricochet\Channel\Control\Proto\ChannelResult
     */
    public function clearOpened(){
      return $this->_clear(2);
    }
    
    /**
     * Get <opened> value
     *
     * @return boolean
     */
    public function getOpened(){
      return $this->_get(2);
    }
    
    /**
     * Set <opened> value
     *
     * @param boolean $value
     * @return \Ricochet\Channel\Control\Proto\ChannelResult
     */
    public function setOpened( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <common_error> has a value
     *
     * @return boolean
     */
    public function hasCommonError(){
      return $this->_has(3);
    }
    
    /**
     * Clear <common_error> value
     *
     * @return \Ricochet\Channel\Control\Proto\ChannelResult
     */
    public function clearCommonError(){
      return $this->_clear(3);
    }
    
    /**
     * Get <common_error> value
     *
     * @return int - \Ricochet\Channel\Control\Proto\ChannelResult\CommonError
     */
    public function getCommonError(){
      return $this->_get(3);
    }
    
    /**
     * Set <common_error> value
     *
     * @param int - \Ricochet\Channel\Control\Proto\ChannelResult\CommonError $value
     * @return \Ricochet\Channel\Control\Proto\ChannelResult
     */
    public function setCommonError( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <error_message> has a value
     *
     * @return boolean
     */
    public function hasErrorMessage(){
      return $this->_has(4);
    }
    
    /**
     * Clear <error_message> value
     *
     * @return \Ricochet\Channel\Control\Proto\ChannelResult
     */
    public function clearErrorMessage(){
      return $this->_clear(4);
    }
    
    /**
     * Get <error_message> value
     *
     * @return string
     */
    public function getErrorMessage(){
      return $this->_get(4);
    }
    
    /**
     * Set <error_message> value
     *
     * @param string $value
     * @return \Ricochet\Channel\Control\Proto\ChannelResult
     */
    public function setErrorMessage( $value){
      return $this->_set(4, $value);
    }
  }
}

