<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: Control.proto
//   Date: 2016-08-05 18:35:13

namespace Ricochet\Channel\Control\Proto {

  class KeepAlive extends \DrSlump\Protobuf\Message {

    /**  @var boolean */
    public $response_requested = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Ricochet.Channel.Control.KeepAlive');

      // REQUIRED BOOL response_requested = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "response_requested";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <response_requested> has a value
     *
     * @return boolean
     */
    public function hasResponseRequested(){
      return $this->_has(1);
    }
    
    /**
     * Clear <response_requested> value
     *
     * @return \Ricochet\Channel\Control\Proto\KeepAlive
     */
    public function clearResponseRequested(){
      return $this->_clear(1);
    }
    
    /**
     * Get <response_requested> value
     *
     * @return boolean
     */
    public function getResponseRequested(){
      return $this->_get(1);
    }
    
    /**
     * Set <response_requested> value
     *
     * @param boolean $value
     * @return \Ricochet\Channel\Control\Proto\KeepAlive
     */
    public function setResponseRequested( $value){
      return $this->_set(1, $value);
    }
  }
}

