<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: Control.proto
//   Date: 2016-08-04 01:45:57

namespace Ricochet\Channel\Control\Proto {

  class OpenChannel extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $channel_identifier = null;
    
    /**  @var string */
    public $channel_type = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Ricochet.Channel.Control.OpenChannel');

      // REQUIRED INT32 channel_identifier = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "channel_identifier";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED STRING channel_type = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "channel_type";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <channel_identifier> has a value
     *
     * @return boolean
     */
    public function hasChannelIdentifier(){
      return $this->_has(1);
    }
    
    /**
     * Clear <channel_identifier> value
     *
     * @return \Ricochet\Channel\Control\Proto\OpenChannel
     */
    public function clearChannelIdentifier(){
      return $this->_clear(1);
    }
    
    /**
     * Get <channel_identifier> value
     *
     * @return int
     */
    public function getChannelIdentifier(){
      return $this->_get(1);
    }
    
    /**
     * Set <channel_identifier> value
     *
     * @param int $value
     * @return \Ricochet\Channel\Control\Proto\OpenChannel
     */
    public function setChannelIdentifier( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <channel_type> has a value
     *
     * @return boolean
     */
    public function hasChannelType(){
      return $this->_has(2);
    }
    
    /**
     * Clear <channel_type> value
     *
     * @return \Ricochet\Channel\Control\Proto\OpenChannel
     */
    public function clearChannelType(){
      return $this->_clear(2);
    }
    
    /**
     * Get <channel_type> value
     *
     * @return string
     */
    public function getChannelType(){
      return $this->_get(2);
    }
    
    /**
     * Set <channel_type> value
     *
     * @param string $value
     * @return \Ricochet\Channel\Control\Proto\OpenChannel
     */
    public function setChannelType( $value){
      return $this->_set(2, $value);
    }
  }
}

