<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: Control.proto
//   Date: 2016-08-04 01:45:57

namespace Ricochet\Channel\Control\Proto\ChannelResult {

  class CommonError extends \DrSlump\Protobuf\Enum {
    const GenericError = 0;
    const UnknownTypeError = 1;
    const UnauthorizedError = 2;
    const BadUsageError = 3;
    const FailedError = 4;
  }
}
