<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: AuthHiddenService.proto
//   Date: 2016-08-04 01:45:56

  \Ricochet\Channel\Control\Proto\OpenChannel::extension(function(){
      // OPTIONAL BYTES Ricochet\Channel\AuthHiddenService\Proto\client_cookie = 7200
    $f = new \DrSlump\Protobuf\Field();
    $f->number    = 7200;
    $f->name      = 'client_cookie';
    $f->type      = \DrSlump\Protobuf::TYPE_BYTES;
    $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
    return $f;
  });
  \Ricochet\Channel\Control\Proto\ChannelResult::extension(function(){
      // OPTIONAL BYTES Ricochet\Channel\AuthHiddenService\Proto\server_cookie = 7200
    $f = new \DrSlump\Protobuf\Field();
    $f->number    = 7200;
    $f->name      = 'server_cookie';
    $f->type      = \DrSlump\Protobuf::TYPE_BYTES;
    $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
    return $f;
  });
